"use strict";
let num1 = 10;
let num2 = 20;
let num3;
let num4 = "40";
let num5 = true;
num3 = num1 + num2;
console.log("Cộng: ", num3);
num3 = num1 - num2;
console.log('====================================');
console.log("Trừ: ", num3);
console.log('====================================');
num3 = num1 * num2;
console.log('====================================');
console.log("Nhân: ", num3);
console.log('====================================');
num3 = num1 / num2;
console.log("Chia: ", num3);
let result = num4 + num5;
console.log('====================================');
console.log("Num4 + Num5: ", result);
console.log('====================================');
